services:
  web:
    image: cosy-app
    build:
      context: .
      args:
        - SECURESECO_PORTAL_IMAGE
    restart:  unless-stopped
    depends_on:
      - dlt
    networks:
      - internal
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./src:/usr/app/src
      - /var/run/docker.sock:/var/run/docker.sock
      - TrustSECO:/root/.gnupg
    env_file: ".env"

  dlt:
    image: dlt-app
    build: ${TRUSTSECO_DLT_GIT_REPO}#${TRUSTSECO_DLT_GIT_BRANCH}
    restart:  unless-stopped
    networks:
      - internal
    ports:
      - "8000:8000"
      - "127.0.0.1:7887:7887"
      - "127.0.0.1:8001:8001"
    volumes:
      - TrustSECO:/root/.lisk
      - TrustSECO:/root/.gnupg
      - TrustSECO:/trustseco
    environment:
      - HOSTNAME=localhost
      - RESET_ON_VERSION_MISMATCH=1

  spider:
    image: spider-app
    build: ${TRUSTSECO_SPIDER_GIT_REPO}#${TRUSTSECO_SPIDER_GIT_BRANCH}
    restart:  unless-stopped
    stop_signal: SIGINT
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - internal
    volumes:
      - TrustSECO:/app/clamav/sockets

  scanner:
    container_name: ClamAV-daemon
    image: 'clamav/clamav:0.104'
    restart:  unless-stopped
    environment:
      - CLAMAV_NO_MILTERD=true
    depends_on:
      - spider
    networks:
      - internal
    volumes:
      - TrustSECO:/run/clamav
      - ./clamav/configs:/etc/clamav

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
    env_file: ".env"
    profiles: ["hosting"]

volumes:
  TrustSECO:
  caddy_data:
  caddy_config:

networks:
  internal:
