- name: prints the gpg keys of the services, so they can be uploaded to github
  hosts: uuservers
  become: yes

  tasks:
    - name: get generated gpg key
      community.docker.docker_compose_v2_exec:
        service: web
        command: curl localhost:3000/api/dlt/get-gpg-key
        project_src: /datadisk/SecureSECO
      register: result
    - name: print gpg key, make sure to restart the server after adding the keys (restart_compose.yml)
      ansible.builtin.debug:
        msg: " {{ inventory_hostname }}: {{ result.stdout }}"
