- name: Clone secureseco repo and run run.sh
  hosts: all
  become: yes

  tasks:
    - ansible.builtin.git:
        repo: 'https://github.com/SecureSECO/SecureSECO'
        dest: /datadisk/SecureSECO
        version: reverse-proxy-and-hosting
    - name: copy .env files
      template:
        src: "{{ inventory_hostname }}.env"
        dest: /datadisk/SecureSECO/.env
        mode: '0644'
    - name: Ensure service is stopped before building/pulling
      community.docker.docker_compose_v2:
        project_src: /datadisk/SecureSECO
        state: absent
    - name: Run the pull/build dependecies script
      ansible.builtin.script: 
        cmd: pull_build_dependecies.sh
        chdir: /datadisk/SecureSECO
    - name: Start service
      community.docker.docker_compose_v2:
        project_src: /datadisk/SecureSECO
        state: present
        build: always
